name: Docker Build Image

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Confirm Building image'
        required: true
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_TOKEN }}
          password: ${{ secrets.DOCKER_USERNAME }}

      - name: Build, tag, and push nginx base
        env:
          ECR_REGISTRY: mudiman
          ECR_REPOSITORY: docker-demo-nginx-base
          IMAGE_TAG: base
        run: |
          cd ${{ github.workspace }}/docker/nginx
          docker build . --file Dockerfile --build-arg PHP_UPSTREAM_CONTAINER=app --build-arg PHP_UPSTREAM_PORT=9000 --tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Build, tag, and push nginx base
        env:
          ECR_REGISTRY: mudiman
          ECR_REPOSITORY: docker-demo-app-base
          IMAGE_TAG: base
        run: |
          cd ${{ github.workspace }}/docker/nginx
          docker build . --file Dockerfile --build-arg PHP_UPSTREAM_CONTAINER=app --build-arg PHP_UPSTREAM_PORT=9000 --tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
